### ISSUE TITLE
Remove old authentication and completely replace with devise

### ISSUE THREAD

**Issue by McEileen** [Tweechable/tweechable_final#103]
Before rolling in devise we had a hand-written log-in/authentication process using sessions.  We still have that in certain places.  It needs to be removed.

**Comment by McEileen** [comment]
Hey, @vkoves, can I close this issue since I approved PR #104 from you?

**Comment by vkoves** [comment]
If my PR fixed this issue completely, then yes.

**Comment by McEileen** [comment]
I checked more thoroughly tonight and the issue is resolved.  Good work. 👍
