### ISSUE TITLE
Can't submit new lesson or edit lessons through the user portal

### ISSUE THREAD

**Issue by McEileen** [Tweechable/tweechable_final#117]
Tonight @TheJhyde pointed out that users currently don't have the ability to submit or edit lessons through the portal.  I think we previously made this change (maybe @vkoves?) because we didn't have final security in place for finalizing content, we currently only have team members submitting content and we weren't sure about including this user portal functionality for MVP.  I will investigate adding the functionality back in - please let me know opinions on whether or not it's for MVP.

**Comment by TheJhyde** [comment]
If we don't want anyone to be able to add content to the site, then we should probably at least comment out all the links and forms for it on the site. There's a lot of functionality on it right now that isn't necessary if all the site does is show the lessons we have.

**Comment by vkoves** [comment]
I am pretty sure the change that was made was requiring users to be admin to submit or edit lessons. The goal was wiki type functionality, which is notated in issue #66. PR #70 made it so only admins could submit lessons I believe.

**Comment by McEileen** [comment]
Hi, I just checked @vkoves is right.  Thanks for the prompty response!  Admin can currently submit new lessons or edit existing lessons.  Is the wiki type functionality a post-MVP goal?  (I realize we may be in the process of deciding this.)

**Comment by vkoves** [comment]
I don't think so. See @kevinpuj commenting on #66 in which he said

> I think, for MVP, we could hone in on 4 - admins publish lessons, and that would be the gateway. We don't imagine a ton of people contributing lessons from outside the group at the beginning.

Also the milestone for MVP does not include issue #66 (see [the MVP Milestone](https://github.com/Tweechable/tweechable_final/milestone/1)) though I am unsure how up to date that is.

**Comment by McEileen** [comment]
I'm closing this issue because it's out of date.  At this point in the project, we are still only uploading lessons from group members.  We do plan to have functionality for users to submit and edit lessons through the user portal in the future.
