### ISSUE TITLE
Update Homepage Twitter Demo to Match Latest Twitter Brand Guide

### ISSUE THREAD

**Issue by vkoves** [Tweechable/tweechable_final#130]
Currently, our homepage features this example of a Twitter conversation:

![screenshot from 2017-10-06 23-34-26](https://user-images.githubusercontent.com/3187531/31304749-f0a15414-aaee-11e7-9947-b98e90bc1a15.png)

Although I'm positive that it was relatively close to the Twitter brand at the time it was made (I recall making it a while back), Twitter has changed significantly since that time. We should update this to match [Twitter's Brand Resources](https://about.twitter.com/en_us/company/brand-resources.html) so that it looks like a proper tweet. This will ensure legal compliance with their brand guidelines and also making it more intuitive that these are tweets.

This should be a fun project, so I'm assigning this to myself if others agree it should be done. @McEileen, do you agree with this issue?

**Comment by McEileen** [comment]
Yes, I agree with this idea.  Thanks for taking it on!

**Comment by vkoves** [comment]
A few things. I started digging into this further and found the lovely [display requirements] for Twitter's tweets, which is very helpful. However, I also wanted to point out a specific section and get feedback. Under their "Don't" section:
> Use mock ups of Tweets that don’t exist on the platform.

Would it be best to leave the styling as is, with it looking somewhat familiar to Twitter but different enough that it wouldn't be problematic with their design principles, or what is best here?

**Comment by McEileen** [comment]
Shoot, I'm not initially sure.  I'm going to research more and follow up with you.  Thanks for looking up the [display requirements](https://developer.twitter.com/en/developer-terms/display-requirements).

**Comment by McEileen** [comment]
I'm looking through old issues and realize I never resolved this with you, @vkoves.  I will do additional research (as we discussed today at our meeting) and let you know by Sunday, January 28.

**Comment by McEileen** [comment]
After doing further research and talking with @vkoves, we decided to stick with the visually out-of-date example tweet conversation.  We are prioritizing following the display requirement to not "use mock ups of tweets that don't exist on the platform."  I am closing the issue.
