### ISSUE TITLE
Creating a general contact form

### ISSUE THREAD

**Issue by lybogany** [Tweechable/tweechable_final#132]
Hi Tweechable Team!

I'll work on creating a general contact form in Ruby. I was thinking to have three fields:
1) Name (limit 100 chars)
2) Email (limit 100 chars)
3) Inquiry (limit 500 chars)

This form would send a formatted email to tweechable@gmail.com. 

Any other ideas or suggestions welcome!

Thanks,
L

**Comment by McEileen** [comment]
I'm closing this because it was resolved by PR #133
