### ISSUE TITLE
Code of Conduct needs to be added to tweechable_final repo

### ISSUE THREAD

**Issue by McEileen** [Tweechable/tweechable_final#23]
Hi, we adopted the Contributors' Covenant as our Code of Conduct https://github.com/Tweechable/tweechable/blob/master/CODE_OF_CONDUCT.md) for the project and it needs to be added to this current repo.  I can add it and then have someone approve the pull request.

**Comment by McEileen** [comment]
I added it and made a pull request! :)

**Comment by vkoves** [comment]
This was merged in, so I'm closing the issue. See pull request #30 or view [the code of conduct in the repository](https://github.com/Tweechable/tweechable_final/blob/master/CODE_OF_CONDUCT.md).
