### ISSUE TITLE
Contact sources and ask for permission to use their work?

### ISSUE THREAD

**Issue by McEileen** [Tweechable/tweechable_final#26]
Would it be helpful to contact people and ask them if we can use their articles/tweet storms/blogs and more in tweet responses?  The ethics around crediting on twitter are foggy to me....  Maybe we should talk more about this in person as a group?

**Comment by kevinpuj** [comment]
This is all taken care of per e-mail conversation with Eileen.  We will not represent any content as our own; quote and/or link to author.
