### ISSUE TITLE
Switch to Cron Jobs for Scheduling

### ISSUE THREAD

**Issue by vkoves** [Tweechable/tweechable_final#31]
From my discussion with everyone, it sounds like we're using Heroku Scheduler to run the bot process every 10 minutes. The bot could probably run more frequently if it was using a cron job, so I'd like to propose moving over to some kind of scheduled process instead of Heroku scheduler. (Also because there are a few issues with Heroku scheduler, such as a no-guarantee state, see [here](https://devcenter.heroku.com/articles/scheduler))

**Comment by McEileen** [comment]
I'm closing this issue because we do not have the resources to work on it in our current project iteration.  If someone wants to tackle this problem in the future, they can open a new issue.
