### ISSUE TITLE
Create a "Getting Started" guide for new team members

### ISSUE THREAD

**Issue by McEileen** [Tweechable/tweechable_final#33]
A "getting started" guide would help new team members to get off the ground and smoothly begin working on Tweechable.

**Potential sections**
 

- System requirements (Ruby version, Rails version, etc.)
- Instructions on how to install needed tools (Rails, Git, a text editor, etc.)
- Links to relevant tutorials (Rails, Ruby, potentially something about twitter API?)
- Guidelines for how to submit a change to Tweechable
 
If you are a new team member and have ideas for what else a "Getting Started" guide should include, please chime in!

**Comment by vkoves** [comment]
Just a general question, would this be located in the google doc, me a markdown document within the repo, or just a section in the README? I'd also ask if there are any rules or guidelines regarding documentation, and releases (e.g. who pushes release and when, who do you contact to get those done, that type of thing). Overall these all seem like good things to have.

By the way, for a nice example of a Getting Started guide for contributors, I'd look at [Bower's Contribution Doc](https://github.com/bower/bower/blob/master/CONTRIBUTING.md).

**Comment by McEileen** [comment]
Apologies for the late reply!  It's been a busy week.  I think that we should have it as a markdown document within the repo, and we should link to it in the README to make it easier to find.  We don't currently have any rules/guidelines for documentation, but I agree that we should have those.  By releases, you mean pushes to the twitter bot itself, correct?  I think we should have guidelines for that, as well as guidelines for getting pull requests to the github code approved.

Thanks for the contribution doc link!  It's good stuff.

**Comment by vkoves** [comment]
This appears to be done, as [the guide](https://github.com/Tweechable/tweechable_final/blob/master/GETTING_STARTED.md) is in the master branch of the repo and the PR was merged in (see PR #40), so I am closing this issue.
