### ISSUE TITLE
Front-end styling for user portal

### ISSUE THREAD

**Issue by McEileen** [Tweechable/tweechable_final#37]
Focus on readability and consistency.

**Comment by javierforero** [comment]
@McEileen  I'll work on this. I've been cooking up some ideas I can share today

**Comment by McEileen** [comment]
Hi @javierforero, long time no see!  At last week's meeting @Ibisita expressed interest in joining the project on the front-end, and I wanted to connect you two.  Please let us know if you're still available to collaborate on tweechable.

**Comment by Ibisita** [comment]
Hi Eileen/Hi Javier,

I'm available this weekend to go through the site online and Git to be able
to make some UI recommendations.
Maybe Javier already did that with his notes.
I've yet to read them because I didn't want to be influenced in case
there's an idea that hadn't been thought of.

Once I pull that together I'll go over the notes and we can talk if
something is executable to figure out whoever can help implementable on the
front end.

Thanks.  Javier, if you have other thoughts let me know! :)
Ibis

**Comment by McEileen** [comment]
Hi @Ibisita, if @javierforero is not available I can meet with you at some point, at hack night or otherwise, to discuss possible front-end changes.  Feel free to DM me through slack if you want to set up a meeting time.  Thanks for your involvement!

**Comment by javierforero** [comment]
Hi @McEileen  sorry I've been out of the loop. @Ibisita nice to meet ya! I am happy to collaborate and brainstorm ideas with you guys. I am available to catch up this week sometime after 5pm cst on Thursday or Friday. 

I can also just this upcoming hacknight. Let me know.

**Comment by McEileen** [comment]
Let's do this upcoming hacknight.  See you both then and there, @ibista and
@javierforero!

**Comment by Ibisita** [comment]
Hi @McEileen & @javierforero, I've been a little out of the loop myself but I was at hack night last week and put a tiny bit of time in to thinking through a concept and wireframe - but still a ways to go and would be good for us to talk and collab. Unfortunately tonight I have orientation but we can touch base on here or slack and catch up during the week. Talk soon :)

**Comment by McEileen** [comment]
HI @Ibisita and @javierforero, I'll be at hacknight next week and can talk before then or beforehand.  Let's shift this logistics planning to slack.  @Ibisita, I don't know if you've joined the chihacknight slack, but if not, here's [the link to join](http://slackme.chihacknight.org/).  Our channel is tweechable-moments.

**Comment by McEileen** [comment]
I'm closing this issue because it is no longer current.  If someone wants to work on a similar issue in the future, please open a new issue.  Thank you!
