### ISSUE TITLE
Links in lessons on portal aren't clickable

### ISSUE THREAD

**Issue by McEileen** [Tweechable/tweechable_final#38]
The links in the lessons aren't clickable. http://tweechable.herokuapp.com/lessons

**Comment by McEileen** [comment]
@alexstevenson19 will work on this! 👍

**Comment by vkoves** [comment]
@alexstevenson19 has started working on this on the branch `clickable_lessons`.

Stuff still to do:
- Fix individual lessons display (e.g. on http://localhost:5000/lessons/6)
- Fix tweet editing to add link field
- Fix tweet creation to add link field (I believe `views/tweets/_form.html` is the place for this)

**Comment by McEileen** [comment]
I'm going to close this issue because a) it appears to no longer be active and b) it is not relevant because we currently don't have lessons displayed in the portal.  (This obviously will change before we launch.)
