### ISSUE TITLE
Request to make tweechable/tweechable_final repo separate from lw334/tweechable repo

### ISSUE THREAD

**Issue by McEileen** [Tweechable/tweechable_final#45]
The current set-up is confusing and causes people to accidentally open pull requests to Lingwei's repo.  We need to do a request to github.

**Comment by vkoves** [comment]
Per this article [about contributons](https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/) (see "Commit was made in a fork") we have to contact [GitHub support](https://github.com/contact). One of the admins will probably have to do this (as they have the level of access that this request would make sense), so @lw334, @kevinpuj, or @McEileen (I'm guessing) this is for you guys.

**Comment by TheJhyde** [comment]
I've submitted a request to Github support. I'll let everyone know if they say anything.

**Comment by TheJhyde** [comment]
Github has processed the issue! Thanks github.

**Comment by lw334** [comment]
Thanks for working on this!
