### ISSUE TITLE
Remove validation so that it doesn't break because of URLs

### ISSUE THREAD

**Issue by kevinpuj** [Tweechable/tweechable_final#5]
Right now, we cut off at X characters, no matter what.  We need to cut off at X actual text characters + one link length.  This is a short issue because we discussed it in person.

**Comment by kevinpuj** [comment]
Thx @TheJhyde

**Comment by TheJhyde** [comment]
Tweets are still getting cut off somewhere in the process. I'll see if I can track down the cause.

**Comment by TheJhyde** [comment]
I tracked it down - it was in tweet submission form. I removed that and put in a warning that pops up when you make a tweet that's long than 126 characters, so people don't make tweets that are too long accidentally.
