### ISSUE TITLE
Tweechable content edit accessibility

### ISSUE THREAD

**Issue by kevinpuj** [Tweechable/tweechable_final#55]
To recreate: 

1. Go to tweechableapp.heroku.com, do NOT log in
2. Navigate to browse lesson (http://tweechable.herokuapp.com/lessons)
3. Click on a lesson (http://tweechable.herokuapp.com/lessons/3)
4. Add "edit" to the URL (ex http://tweechable.herokuapp.com/lessons/3/edit)

Expected result: shouldn't be allowed to!
Actual result: You can edit!

**Comment by adrianmui** [comment]
i have solved this in my pull request on nov 8th 840pm.

**Comment by TheJhyde** [comment]
Looks good to me!
