### ISSUE TITLE
Add optional process for recommended "follows" on a specific topic

### ISSUE THREAD

**Issue by kevinpuj** [Tweechable/tweechable_final#56]
Taking this out of #47

- FOLLOWS (optional) - Names of accounts to follow to learn more
  ---->  `Ex: Please follow @devcolororg or @ghc to learn more`

**Comment by jesolutions** [comment]
Discussed with @alexstevenson19 and decided a technical solution was not necessary.  Rejecting this issue.

**Comment by kevinpuj** [comment]
Discussed with @alexstevenson19 and decided a technical solution was not necessary. Rejecting this issue.
