### ISSUE TITLE
Create functionality to allow for hashtag suggestions

### ISSUE THREAD

**Issue by kevinpuj** [Tweechable/tweechable_final#58]
Related to Lingwei's idea from the roadmap: Lesson Model: the model currently allows not having any tweets. I want to keep it this way so we can at least collect interesting lessons (hash tag ideas) that others can contribute to. But we should display something like “This lesson doesn’t have any tweets yet! Please contribute to make it better!”

This would probably work by:

- Creating specific syntax where a Twitter user could @mention tweechable (e.g. "@tweechable suggest #diversifyVC
- Tweechable creates an empty lesson with that hashtag (if one doesn't exist)
- Tweechable says: "thanks! do you have any suggestions for links or resources that should be a part of this lesson?  please tweet them at me!"
- Tweechable adds any links or tweets as tweets within the hashtag

**Comment by McEileen** [comment]
I'm closing this issue because it is no longer current and we do not currently have the team resources to work on it.  If someone wants to work on a similar issue in the future, please open a new issue and comment that you are working on it.  Thank you!
