### ISSUE TITLE
Allow for link shortening in tweechable lessons

### ISSUE THREAD

**Issue by kevinpuj** [Tweechable/tweechable_final#64]
Twitter does automatic link shortening.  bit.ly links are not reliable or stable enough in the long term, especially with the new reply chain model.

We want a tweechable content creator to be able to easily upload content and know that it will fit in the 140 character limit.

I believe this would involve:

- Changing the character limit for tweechable lessons from a static 140 characters to a dynamic amount based on the number of characters that are taken up by URLs in the tweet
- Figuring out how to detect separate URLs in a tweet (www.bbc.com and bbc.com both get shortened)

Here is more information: https://dev.twitter.com/basics/tco

**Comment by McEileen** [comment]
I'm closing this issue because it is no longer current and we do not currently have the team resources to work on it.  If someone wants to work on a similar issue in the future, please open a new issue and comment that you are working on it.  Thank you!
