### ISSUE TITLE
Security Needs Revision

### ISSUE THREAD

**Issue by vkoves** [Tweechable/tweechable_final#66]
So we need to take a second look at our security, especially looking towards making Tweechable an open wiki-style platform.

In these regards, the following restrictions should be in place:

1. Anyone should be able to make a lesson in an unpublished state
2. Anyone should be able to edit lessons they have made
3. Anyone should be able to suggest edits to any lesson
4. Admins should be able to publish lessons
5. Admins should be able to edit any lesson
6. Admins should be able to approve edits to lessons

Note that "anyone" means any signed in user.

**Comment by kevinpuj** [comment]
I think, for MVP, we could hone in on 4 - admins publish lessons, and that would be the gateway.  We don't imagine a ton of people contributing lessons from outside the group at the beginning.

**Comment by vkoves** [comment]
I believe 4 was taken care of by @TheJhyde in PR #70 anyway, so this is definitely beyond MVP

**Comment by McEileen** [comment]
Restrictions 1-6 are still in the roadmap for the project at the later point.  However, I am closing this issue because it is not currently relevant.
