### ISSUE TITLE
Add Travis CI to repo

### ISSUE THREAD

**Issue by mwgalloway** [Tweechable/tweechable_final#77]
Adding Travis CI will provide continuous integration and run our test suite every time we make a pull request.

**Comment by TheJhyde** [comment]
@mwgalloway is there anything else that needs to be done here? Should we close this issue?

**Comment by vkoves** [comment]
I'd ideally like to get the badge added to the README so that we can see build status

**Comment by vkoves** [comment]
Closed this, since I added the badge to the README in PR #83
