### ISSUE TITLE
Create a staging server on heroku

### ISSUE THREAD

**Issue by TheJhyde** [Tweechable/tweechable_final#81]
We can make an instance of the program seperate from the main one to test updates on production without breaking the main app.

**Comment by McEileen** [comment]
Hi @TheJhyde, is it all right if I close this, since we have the staging app in heroku now?  Also, I mentioned the staging server in a change to the readme, if you want to review and close that PR.

**Comment by McEileen** [comment]
I'm closing this issue since we now have a staging server in Heroku
