### ISSUE TITLE
Work on SEO Improvements

### ISSUE THREAD

**Issue by vkoves** [Tweechable/tweechable_final#88]
Tweechable has no meta description at the moment so we show up on Google like this:

![screenshot from 2017-01-24 20-43-56](https://cloud.githubusercontent.com/assets/3187531/22275944/e4eb42d4-e275-11e6-8c64-5a62284ea7c6.png)

We should add a meta description and do an overall SEO audit to make sure Tweechable is friendly with web crawlers.

**Comment by McEileen** [comment]
Hey, I just deployed the code that includes this meta description, but our search result hasn't changed to reflect the description.  (See below description) . @vkoves, any idea how long this change takes to go into effect?
<img width="739" alt="screen shot 2017-09-12 at 7 45 22 pm" src="https://user-images.githubusercontent.com/5529982/30354576-f559a98e-97f2-11e7-89d7-8b21424f54dc.png">

I'm going to leave this issue open until it's resolved.

**Comment by vkoves** [comment]
Replied in person, but worth documenting:
This should update in time as Google recrawls your site. Additionally, you can use the Google Search Console to manually request reindexing. You can read more about that via [their help article] on the subject.

**Comment by McEileen** [comment]
I'm closing this issue because the SEO improvement were made.  (This issue probably should have been closed back in September 2017)
